{% raw %}---
- name: install postgres packages for Ubuntu
  apt:
    pkg: "{{ item }}"
    state: installed
    update-cache: yes
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: setup database
  sudo_user: postgres
  postgresql_db:
    db: "{{ pg_db }}"
    encoding: 'UTF-8'
    lc_collate: 'en_US.UTF-8'
    lc_ctype: 'en_US.UTF-8'
    template: 'template0'
    state: present

- name: add hstore
  sudo_user: postgres
  shell: psql {{ pg_db }} -c "CREATE EXTENSION IF NOT EXISTS hstore;"
  when: pg_hstore

- name: grant access for database to user
  sudo_user: postgres
  postgresql_user:
    db: "{{ pg_db }}"
    user: "{{ pg_user }}"
    password: "{{ pg_password }}"
    role_attr_flags: "CREATEDB,SUPERUSER"
    state: present

- name: ensure postgres is running
  service: name=postgresql state=started enabled=yes{% endraw %}
