{% raw %}---
# roles/common/defaults/main.yml
common_timezone: {% endraw %}{{ cookiecutter.timezone }}{% raw %}

lc_lang: "en_US.UTF-8"
lc_all: "en_US.utf8"
lc_ctype: "en_US.utf8"
lc_collate: "en_US.utf8"

base_ubuntu:
  common:
    apt_packages:
      - build-essential
      - git
      - htop
      - curl
      - python-dev
      - python3.9
      - python3.9-dev
      - python-setuptools
      - python3-pip
      - sysstat
      - vim
      - fail2ban
      - libjpeg-dev
      - libtiff5-dev
      - zlib1g-dev
      - libfreetype6-dev
      - liblcms2-dev
      - postgresql-client
      - libpq-dev
      - libicu60
      - libreadline-dev
      - ca-certificates
{% endraw %}
