---
# roles/common/defaults/main.yml
common_timezone: {{cookiecutter.timezone}}

lang: "en_US.utf8"
lc_all: "en_US.utf8"
lc_ctype: "en_US.utf8"
lc_collate: "en_US.utf8"
ubuntu_release: "trusty"

base_ubuntu:
  common:
    apt_packages:
      - build-essential
      - git
      - htop
      - python-dev
      - python-setuptools
      - python-virtualenv
      - python3
      - python3-dev
      - python3-setuptools
      - python3-pip
      - sysstat
      - vim
      - fail2ban
      - libjpeg-dev
      - libtiff4-dev
      - zlib1g-dev
      - libfreetype6-dev
      - liblcms2-dev
      - postgresql-client
      - libpq-dev
      - postgis
