{% raw %}---
- name: copy celery.log logrotate
  template: src=celery.log.j2
            dest=/etc/logrotate.d/celery-{{ project_namespace }}
            mode=644
  tags: ['configure', 'celery']

- name: make sure log directory exists
  file: path={{ celery_log_dir }} state=directory owner={{celery_user}} group={{celery_group}} mode=751 recurse=yes
  tags: ['configure', 'celery']

- name: manually create the initial virtualenv
  command: virtualenv {{ venv_path }} -p python3 creates={{ venv_path }}
  become: false
  tags: ['celery']

- name: ensure celery package is installed
  pip: name=celery state=present executable={{ venv_path }}/bin/pip
  become: false
  tags: ['celery']

- name: copy celery service
  template: src=celery.service.j2 dest=/etc/systemd/system/celery-{{ project_namespace }}.service
  tags: ['celery']

- name: copy celery beat service
  template: src=celerybeat.service.j2 dest=/etc/systemd/system/celerybeat-{{ project_namespace }}.service
  tags: ['celery']

- name: start celery service
  shell: service celery-{{ project_namespace }} start
  tags: ['celery']

- name: start celery service
  shell: service celerybeat-{{ project_namespace }} start
  tags: ['celery']
{% endraw %}
