# For more information about the configurations used in this file, please
# see the Travis CI documentation: https://docs.travis-ci.com

language: python
sudo: false
python:
- '3.6.4'

addons:
  postgresql: "9.5"
  apt:
    packages:
      - postgresql-9.5-postgis-2.3

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  {% if cookiecutter.add_ansible.lower() == 'y' %}- pip install ansible{% endif %}
  - pip install -r requirements/development.txt

before_script:
- export DATABASE_URL=postgres://postgres@localhost/{{ cookiecutter.main_module }}
- psql -c "CREATE DATABASE {{ cookiecutter.main_module }};" -U postgres
{%- if cookiecutter.postgis.lower() == 'y' %}
- psql -c "CREATE EXTENSION postgis;" -U postgres -d {{ cookiecutter.main_module }}
{%- endif %}

script:
- flake8
- py.test --cov -v --tb=native
{% if cookiecutter.add_ansible.lower() == 'y' %}- ansible-playbook -i provisioner/hosts provisioner/site.yml --syntax-check{% endif %}

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]

{%- if cookiecutter.enable_heroku_deployment.lower() == 'y' %}
deploy:
  provider: heroku
  buildpack: python
  strategy: api
  api_key:
    # travis encrypt $(heroku auth:token) --add deploy.api_key
    secure: <add_heroku_auth_token_here>
  app:
    master: {{ cookiecutter.main_module }}-dev
    qa: {{ cookiecutter.main_module }}-qa
    prod: {{ cookiecutter.main_module }}-prod
  on:
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.github_repository }}
{% endif %}
