language: python
sudo: false
python:
- '2.7'
addons:
  postgresql: "9.3"

before_script:
- export DATABASE_URL=postgres://postgres@localhost/{{ cookiecutter.main_module }}
- export DJANGO_SECRET=`openssl rand -base64 32`
- psql -c "CREATE DATABASE {{ cookiecutter.main_module }};" -U postgres

install:
  - pip install ansible
  - pip install -r requirements/development.txt

script:
- flake8
- coverage run --source={{ cookiecutter.main_module }} --omit='*tests*,*commands*,*migrations*,*admin*,*config*,*wsgi*' -m py.test -v --tb=native
- ansible-playbook -i provisioner/hosts provisioner/site.yml --syntax-check
- coverage report

notifications:
  email:
    on_success: change  # [always|never|change]
    on_failure: always  # [always|never|change]
deploy:
  provider: heroku
  buildpack: python
  strategy: api
  api_key:
    # travis encrypt $(heroku auth:token) --add deploy.api_key
    secure: <add_heroku_auth_token_here>
  app:
    master: {{ cookiecutter.main_module }}-dev
    qa: {{ cookiecutter.main_module }}-qa
    prod: {{ cookiecutter.main_module }}-prod
  on:
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.github_repository }}
  run:
    - "python manage.py migrate"
