{%raw%}---
# htpasswd module needs passlib
- name: Install passlib
  pip: name=passlib

- name: Create htpasswd file
  htpasswd:
    path: "{{ htpasswd_file_path }}"
    name: "{{ nginx_docs_username }}"
    password: "{{ nginx_docs_password }}"{%endraw%}
