{% raw %}---
- name: ensure gunicorn config directory exists
  file: path={{ gunicorn_conf_path }}
        owner=root
        group=root
        mode=755
        state=directory

- name: copy gunicorn configuration
  template: src=gunicorn.conf.py.j2
            dest={{ gunicorn_conf_path }}/gunicorn.conf.py
            mode=644
  notify: restart gunicorn

- name: copy supervisor config for gunicorn
  template: src=supervisor_gunicorn.conf.j2 dest=/etc/supervisor/conf.d/gunicorn.conf
  notify: restart supervisor
  tags: ['deploy', 'gunicorn']
{% endraw %}
