{% raw %}---
- name: Download NodeSource Setup script
  get_url:
    url: "https://deb.nodesource.com/setup_{{ webpack_node_version }}.x"
    dest: "/tmp/node_setup_{{ webpack_node_version }}.x"
  become: false

- name: Run NodeSource setup script
  command: "bash /tmp/node_setup_{{ webpack_node_version }}.x"
  become: true

- name: Update apt-cache separately
  shell: apt update
  become: yes

- name: Add PPA for node 10
  command: "curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh"
  become: true

- name: Update cache for installing Node
  command: "sudo bash nodesource_setup.sh"
  become: true

- name: Install Node.js
  apt:
    pkg: nodejs
    state: present

- name: Make sure webpack stats file exists
  file:
    path: "{{ project_path }}/webpack-stats.json"
    state: touch
    owner: "{{user}}"
    group: "{{uwsgi_group}}"

- name: Install packages based on package.json.
  npm:
    path: "{{ project_path }}"
    global: no
  become: false
  tags: ['deploy']

- name: Run build webpack
  command: "npm run build"
  become: false
  tags: ['deploy']
  environment:
    NODE_ENV: production
  args:
   chdir: "{{ project_path }}"

- name: collect static
  django_manage:
    command: "collectstatic --no-input -i js -i css -i server.js -i webpack.config.js"
    app_path: "{{ project_path }}"
    virtualenv: "{{ venv_path }}"
  become: false
  tags: ['deploy']
{% endraw %}
