# Install Node.js using packages crafted by NodeSource
---
- name: Download NodeSource Setup script
  get_url: url=https://deb.nodesource.com/setup_6.x dest=/tmp/node_setup_6.x
  become: false

- name: Run NodeSource setup script
  command: bash /tmp/node_setup_6.x
  become: true

- name: Update apt-cache separately
  shell: apt update
  become: yes

- name: Install Node.js
  apt:
    pkg: nodejs
    state: present
